version: 2.1

orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@3.0.1

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Check PowerShell version
          run: $PSVersionTable.PSVersion
      - run:
          name: Try install mysql
          run: Find-Package mysql | Install-Package
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
workflows:
  build_app:
    jobs:
      - build
