version: 2.1

orbs:
  win: circleci/windows@2.4.0
  node: circleci/node@3.0.1

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Check PowerShell version
          command: $PSVersionTable.PSVersion
      - run:
          name: Check choco
          command: choco --version
      - run: 
          name: Install mysql
          command: choco install mysql
      - run:
          name: Test MySQL
          command: |
            mysql -uroot -e 'CREATE DATABASE mysql_test;'
            mysql -uroot -e 'CREATE DATABASE mysql_test2;'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
workflows:
  build_app:
    jobs:
      - build
